version: '3.9'
services:
  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    container_name: git-sync
    env_file:
      - .env
    environment:
      - GIT_REPO=${GIT_REPO}
      - GIT_SYNC_BRANCH=${GIT_SYNC_BRANCH}
      - GIT_SYNC_ROOT=${GIT_SYNC_ROOT}
      - GIT_SYNC_WAIT=${GIT_SYNC_WAIT}
      - GITSYNC_ONE_TIME=false
    volumes:
      - ./repo:${GIT_SYNC_ROOT}
      - ./entrypoint.sh:/entrypoint.sh
      - ~/.ssh/id_rsa:/etc/git-secret/ssh:ro
      - ~/.ssh/known_hosts:/etc/git-secret/known_hosts:ro
    command: ["/bin/sh", "/entrypoint.sh"]
