version: '3.9'
services:
  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    container_name: git-sync
    env_file:
      - .env
    environment:
      - GIT_SYNC_REPO=${GIT_SYNC_REPO}
      - GIT_SYNC_BRANCH=${GIT_SYNC_BRANCH}
      - GIT_SYNC_ROOT=${GIT_SYNC_ROOT}
      - GIT_SYNC_WAIT=${GIT_SYNC_WAIT}
      - GIT_SYNC_ONE_TIME=false
    volumes:
      - ${DEST_DIR}:${GIT_SYNC_ROOT}
      - ./entrypoint.sh:/entrypoint.sh
      - ~/.ssh/git-sync:/etc/git-secret/ssh:ro
      - ~/.ssh/known_hosts:/etc/git-secret/known_hosts
    command: ["/bin/sh", "/entrypoint.sh"]
  watcher:
    image: alpine
    volumes:
      - ${UPDATE_REPO_DIR}:/repo
    entrypoint: ["/bin/sh", "/repo/build.sh"]
